" Make sure you use single quotes
Plug 'godlygeek/tabular'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-surround'
Plug 'junegunn/fzf'
Plug 'tomtom/tcomment_vim'
Plug 'rking/ag.vim'
Plug 'airblade/vim-gitgutter'
Plug 'terryma/vim-multiple-cursors'
Plug 'benekastah/neomake'
Plug 'scrooloose/nerdtree'
Plug 'bling/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'tpope/vim-endwise'
Plug 'Shougo/deoplete.nvim'
Plug 'tpope/vim-dispatch'
Plug 'NLKNguyen/papercolor-theme'
